dict set KD_Normalized ALA 0.7 
dict set KD_Normalized ARG 0.0 
dict set KD_Normalized ASN 0.11 
dict set KD_Normalized ASP 0.11 
dict set KD_Normalized CYS 0.78 
dict set KD_Normalized GLN 0.11 
dict set KD_Normalized GLU 0.11 
dict set KD_Normalized GLY 0.46 
dict set KD_Normalized HIS 0.14 
dict set KD_Normalized ILE 1.0 
dict set KD_Normalized LEU 0.92 
dict set KD_Normalized LYS 0.07 
dict set KD_Normalized MET 0.71 
dict set KD_Normalized PHE 0.81 
dict set KD_Normalized PRO 0.32 
dict set KD_Normalized SER 0.41 
dict set KD_Normalized THR 0.42 
dict set KD_Normalized TRP 0.4 
dict set KD_Normalized TYR 0.36 
dict set KD_Normalized VAL 0.97 

dict set EW_Normalized ALA 0.19 
dict set EW_Normalized ARG 1.0 
dict set EW_Normalized ASN 0.55 
dict set EW_Normalized ASP 0.58 
dict set EW_Normalized CYS 0.28 
dict set EW_Normalized GLN 0.57 
dict set EW_Normalized GLU 0.54 
dict set EW_Normalized GLY 0.23 
dict set EW_Normalized HIS 0.46 
dict set EW_Normalized ILE 0.0 
dict set EW_Normalized LEU 0.08 
dict set EW_Normalized LYS 0.74 
dict set EW_Normalized MET 0.19 
dict set EW_Normalized PHE 0.05 
dict set EW_Normalized PRO 0.32 
dict set EW_Normalized SER 0.4 
dict set EW_Normalized THR 0.37 
dict set EW_Normalized TRP 0.15 
dict set EW_Normalized TYR 0.29 
dict set EW_Normalized VAL 0.08 

dict set MF_Normalized ALA 0.29 
dict set MF_Normalized ARG 0.78 
dict set MF_Normalized ASN 0.75 
dict set MF_Normalized ASP 0.68 
dict set MF_Normalized CYS 0.35 
dict set MF_Normalized GLN 0.69 
dict set MF_Normalized GLU 0.51 
dict set MF_Normalized GLY 0.52 
dict set MF_Normalized HIS 0.92 
dict set MF_Normalized ILE 0.08 
dict set MF_Normalized LEU 0.05 
dict set MF_Normalized LYS 1.0 
dict set MF_Normalized MET 0.19 
dict set MF_Normalized PHE 0.0 
dict set MF_Normalized PRO 0.09 
dict set MF_Normalized SER 0.53 
dict set MF_Normalized THR 0.52 
dict set MF_Normalized TRP 0.24 
dict set MF_Normalized TYR 0.15 
dict set MF_Normalized VAL 0.19 