dict set KD_Normalized ALA 0.70
dict set KD_Normalized CYS 0.78
dict set KD_Normalized ASP 0.11
dict set KD_Normalized GLU 0.11
dict set KD_Normalized PHE 0.81
dict set KD_Normalized GLY 0.46
dict set KD_Normalized HIS 0.14
dict set KD_Normalized ILE 1.00
dict set KD_Normalized LYS 0.07
dict set KD_Normalized LEU 0.92
dict set KD_Normalized MET 0.71
dict set KD_Normalized ASN 0.11
dict set KD_Normalized PRO 0.32
dict set KD_Normalized GLN 0.11
dict set KD_Normalized ARG 0.00
dict set KD_Normalized SER 0.41
dict set KD_Normalized THR 0.42
dict set KD_Normalized VAL 0.97
dict set KD_Normalized TRP 0.40
dict set KD_Normalized TYR 0.36

dict set EW_Normalized ALA 0.81
dict set EW_Normalized CYS 0.73
dict set EW_Normalized ASP 0.43
dict set EW_Normalized GLU 0.47
dict set EW_Normalized PHE 0.95
dict set EW_Normalized GLY 0.77
dict set EW_Normalized HIS 0.55
dict set EW_Normalized ILE 1.00
dict set EW_Normalized LYS 0.28
dict set EW_Normalized LEU 0.92
dict set EW_Normalized MET 0.81
dict set EW_Normalized ASN 0.46
dict set EW_Normalized PRO 0.68
dict set EW_Normalized GLN 0.44
dict set EW_Normalized ARG 0.00
dict set EW_Normalized SER 0.61
dict set EW_Normalized THR 0.64
dict set EW_Normalized VAL 0.92
dict set EW_Normalized TRP 0.86
dict set EW_Normalized TYR 0.72
